insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("MacBook Pro", "computer", 35000, "애플", 6, "애플의 맥북 프로")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("그램", "computer", 15000, "LG", 8, "올 데이 그램")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("UHD TV", "home_appliance", 25000, "삼성", 10, "삼성의 UHD TV")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("심슨 하우스", "general_merchandise", 800, "레고", 2, "레고 심슨 하우스")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("V7", "home_appliance", 10000, "다이슨", 3, "엄청난 흡입력")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("AirPod", "general_merchandise", 2500, "애플", 6, "애플의 와이어리스 이어폰")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("iPad Air", "general_merchandise", 5000, "애플", 9, "애플의 테블릿")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Galaxy S20", "computer", 15000, "삼성", 7, "삼성의 최신 스마트폰")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("PS4 Pro", "general_merchandise", 4500, "소니", 12, "소니의 콘솔 게임기")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Xbox one", "general_merchandise", 5000, "MS", 8, "MS의 콘솔 게임기")